const paragraphs=[
    "This is another great story that teaches a lesson that written for kids but adults can enjoy, too. The story tells of a grasshopper who lounges around all summer while his friend the ant prepares for the winter. When winter comes, the two friends end up in very different situations. The moral is that those who save up during the good times will get to enjoy the benefits when times are bad.",
    "This very short story from India was originally written in Sanskrit (an ancient language). When a group of doves is caught in a hunter’s net, they must work together as a team to escape from the hunter’s clutches.You can listen to a reading of the story as you read along on this website. Good grades are most important for being accepted.",
    "This modern story is about a young woman named Penny who is anxious about going to her family’s annual reunion barbecue. But despite screaming children and arguing cousins, Penny ends up happy that she came to the reunion when she starts a conversation with a handsome man.The story is written in simple English, using only the present tense, so it’s perfect for beginners.",
    "This classic children’s story is about two mice, one from the country and one from the city. Both mice think that the other mouse is so lucky to live in what they think is a wonderful place. The two mice decide to visit each other in their homes. It turns out that the country mouse has a difficult time in the city, and the city mouse struggles in the country.",
    "This is a story that every English-speaking child knows. It’s about a little girl who meets a wolf in the forest while going to see her sick grandmother. The wolf pretends to be her grandmother in order to trick the little girl.Thinking about today's high cost of living makes this seem an impossible task for most. Good grades are most important for being accepted.",
    "The bikers rode down the long and narrow path to reach the city park. When they reached a good spot to rest, they began to look for signs of spring. The sun was bright, and a lot of bright red and blue blooms proved to all that warm spring days were the very best. Spring rides were planned. They had a burger at the lake and then rode farther up the mountain.",
    "Neither the boy nor the bike got hurt. After a brief stop, everyone was ready to go on. All the bikers enjoyed the nice view when they came to the top. All the roads far below them looked like ribbons. A dozen or so boats could be seen on the lake. It was very quiet and peaceful and no one wished to leave.Good grades are most important for being accepted.",
    "As they set out on their return, they all enjoyed the ease of pedaling. The bikers came upon a new bike trail. This route led to scenery far grander than that seen from the normal path. The end of the day brought laughs and cheers from everyone. The fact that each person was very, very tired did not keep anyone from eagerly planning for the exciting ride to come.",
    "One morning my friend and I were thinking about how we could plan our summer break away from school. Driving from our own state to several nearby states would help to expand our limited funds. Inviting six other friends to accompany us would lower our car expenses. Stopping at certain sites would also help us stretch our truly limited travel budget. ",
    "I found it difficult to imagine that during my lifetime I might well earn at least one-half million dollars. It is also possible that I might spend as much as one-half million during the same period. The really difficult thing for me to do will be to save more of the half-million than I spend. Thinking about today's high cost of living makes this seem an impossible task for most.",
    "Last week I asked a friend to talk with me and a girl-friend about college. Our friend is the Dean of Women at a nearby college. The Dean and her staff spend much of their time talking to students who plan to go to college. The first thing she said was to work very hard each day in high school. Good grades are most important for being accepted.",
    "Hunt and peck (two-fingered typing), also known as Eagle Finger, is a common form of typing in which the typist presses each key individually. Instead of relying on the memorized position of keys, the typist must find each key by sight. Use of this method may also prevent the typist from being able to see what has been typed without glancing away from the keys.",
    "Although good accuracy may be achieved, any typing errors that are made may not be noticed immediately due to the user not looking at the screen. There is also the disadvantage that because fewer fingers are used, those that are used are forced to move a much greater distance.Good grades are most important for being accepted."
]